# Generated by Django 3.2 on 2021-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echallan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challans',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
