# Generated by Django 3.2 on 2021-05-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echallan', '0002_alter_challans_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challans',
            name='phonenumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
